site_name: WebCorC - Wiki
site_url: https://corc.informatik.kit.edu
repo_url: https://github.com/KIT-TVA/WebCorC

theme:
  name: material
  color_mode: auto
  logo: figures/webcorc.png
  favicon: figures/favicon.png
  user_color_mode_toggle: true
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji

nav:
  - Home:
    - Overview: index.md
    - Publications: home/pubs.md
    - About:
      - People: home/members.md
      - Contact: home/contact.md
      - References: home/references.md
  - Approach:
    - CbC:
      - Theory: theory/cbc/theory.md
      - Practical Example: theory/cbc/example.md
    - XbC:
      - Theory: theory/xbc/xbctheory.md
  - WebCorC:
    - Overview:  webcorc/webcorc-overview.md
    - Getting Started: webcorc/gettingstarted.md
    - Features:
      - AI Chat: webcorc/ai-chat.md
  - CorC (Eclipse):
    - Overview: corc/corc-overview.md
    - Getting Started: corc/gettingstarted.md
    - Case Studies: corc/casestudies.md
    - Features:
      - Code Generation: corc/code-conversion.md
      - Counterexample Generation: corc/counterexamples.md
      - Editors: corc/editors.md
      - Mutation Generation: corc/mutation.md
      - Proof Statistics: corc/proof-stats.md
      - Project Types: corc/project-types.md
      - Related Work: corc/related-work.md
      - Testing: corc/testing.md
      - Verification: corc/verification.md