site_name: WebCorC - Wiki
site_url: https://corc.informatik.kit.edu
repo_url: https://github.com/KIT-TVA/WebCorC

theme:
  name: material
  color_mode: auto
  logo: figures/webcorc.png
  favicon: figures/favicon.png
  user_color_mode_toggle: true
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji

nav:
  - Home:
    - Overview: index.md                              #done
    - Publications: home/pubs.md                      #done
    - About:                                          
      - People: home/members.md                       #done
      - Contact: home/contact.md                      #done
      - References: home/references.md                # todo for some books like kw12, key etc
  - Approach:
    - CbC:
      - Theory: theory/cbc/theory.md                  #done
      - Practical Example: theory/cbc/example.md      # todo need to throw out eclipse corc example
#    - XbC:
#      - Theory: theory/xbc/xbctheory.md
  - WebCorC:
    - Overview:  webcorc/webcorc-overview.md          # todo
    - Getting Started: webcorc/gettingstarted.md      # todo
#    - Features:
#      - AI Chat: webcorc/ai-chat.md
  - CorC (Eclipse):
    - Overview: corc/corc-overview.md                 # todo need clean up and splitting into subpages
    - Getting Started: corc/gettingstarted.md         # todo
    - Case Studies: corc/casestudies.md               # todo
#    - Features:
#      - Code Generation: corc/code-conversion.md
#      - Counterexample Generation: corc/counterexamples.md
#      - Editors: corc/editors.md
#      - Mutation Generation: corc/mutation.md
#      - Proof Statistics: corc/proof-stats.md
#      - Project Types: corc/project-types.md
#      - Related Work: corc/related-work.md
#      - Testing: corc/testing.md
#      - Verification: corc/verification.md